# -*- coding: utf-8 -*-
"""UI action contract for the media-library dialog view."""
from __future__ import annotations

from typing import Protocol

class MediaLibraryDialogActions(Protocol):
    def update_enabled_state(self, enabled: bool) -> None: ...
    def browse_db_path(self) -> None: ...
    def browse_jellyfin_db(self) -> None: ...
    def create_empty_database(self) -> None: ...
    def import_jellyfin(self) -> None: ...
    def scan_storage_paths(self) -> None: ...
    def abort_storage_scan(self) -> None: ...
    def scan_nfo_light(self) -> None: ...
    def scan_nfo_full(self) -> None: ...
    def abort_nfo_scan(self) -> None: ...
    def export_database(self) -> None: ...
    def export_database_csv(self) -> None: ...
    def normalize_stream_types(self) -> None: ...
    def cleanup_inactive_items(self) -> None: ...
    def save(self) -> None: ...
    def remove_mapping_rows(self) -> None: ...
    def fill_mapping_from_storage_paths(self) -> None: ...
    def save_mappings(self) -> None: ...
    def run_search(self) -> None: ...
    def export_search_csv(self) -> None: ...
    def save_current_search(self) -> None: ...
    def load_saved_search(self) -> None: ...
    def delete_saved_search(self) -> None: ...
    def run_sql(self) -> None: ...
    def save_current_sql(self) -> None: ...
    def load_saved_sql(self) -> None: ...
    def delete_saved_sql(self) -> None: ...
    def show_sql_help(self) -> None: ...
    def export_sql_help(self) -> None: ...
    def save_and_close(self) -> None: ...
    def add_mapping_row(self, mapping) -> None: ...
